apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accountstack.fullname" . }}-auth
  labels:
    {{- include "accountstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.auth.jwtSecret | quote }}
  auth-username: {{ .Values.auth.username | quote }}
  auth-password: {{ .Values.auth.password | quote }}
  cloudbees-fm-key: {{ .Values.cloudbees.fmKey | quote }}
